openapi: 3.0.3
info:
  title: API proposal
  description: |-
    A proposal for the API based on the Designs
  version: 0.0.1
tags:
  - name: aircraft
  - name: flight
  - name: maintenance
  - name: team
  - name: highlight
  - name: fleet
paths:
  /aircraft/:
    get:
      tags:
        - aircraft
      summary: Get all owned aircrafts
      responses:
        '200':
          description: The last airport is used to set the location marker on the map if the flight is not contained in /flight/active/ or /maintenance/
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aircraft'

  /aircraft/{id}/:
    get:
      tags:
        - aircraft
      summary: Get aircraft by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Aircraft details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Aircraft'

  /aircraft/{id}/crew/:
    get:
      tags:
        - aircraft
      summary: Get crew of aircraft by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of crew members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /aircraft/{id}/impressions/:
    get:
      tags:
        - aircraft
      summary: Get impressions of aircraft by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of impressions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Impression'

  /flight/active/:
    get:
      tags:
        - flight
      summary: Get list of active flights
      responses:
        '200':
          description: This endpoint is called every few minutes while the user is in the app. The route contains locations that were tracked from the beginning of the flight till now.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ActiveFlight'

  /flight/:
    get:
      tags:
        - flight
      summary: Get list of flights
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: till
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of flights
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Flight'
  /maintenance/:
    get:
      tags:
        - maintenance
      summary: Get list of maintenances
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
        - name: till
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of maintenances
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Maintenance'                

  /team/contact:
    get:
      tags:
        - team
      summary: Get list of contacts
      responses:
        '200':
          description: A list of contacts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /team/:
    get:
      tags:
        - team
      summary: Get list of team members
      responses:
        '200':
          description: A list of team members
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'

  /fleet/:
    get:
      tags:
        - fleet
      summary: Get list of fleet
      responses:
        '200':
          description: A list of aircrafts in the fleet
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aircraft'

  /fleet/sale:
    get:
      tags:
        - fleet
      summary: Get list of aircrafts for sale
      responses:
        '200':
          description: A list of aircrafts for sale
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Aircraft'

  /highlight/:
    get:
      tags:
        - highlight
      summary: Get list of highlights
      parameters:
        - name: page
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A list of highlights
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HighlightResponse'

  /highlight/feedback:
    post:
      tags:
        - highlight
      summary: Send feedback
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Feedback'
      responses:
        '200':
          description: Feedback sent successfully
components:
  schemas:
    Location:
      type: object
      properties:
        lat:
          type: string
        long:
          type: string
      required:
        - lat
        - long

    Airport:
      type: object
      properties:
        name:
          type: string
        identifier:
          type: string
        location:
          $ref: '#/components/schemas/Location'
      required:
        - name
        - identifier
        - location

    Person:
      type: object
      properties:
        name:
          type: string
        type:
          $ref: '#/components/schemas/PersonType'
        email:
          type: string
          nullable: true
        telephone:
          type: string
          nullable: true
        missionStatement:
          type: string
      required:
        - name
        - type
        - missionStatement

    Maintenance:
      type: object
      properties:
        airport:
          $ref: '#/components/schemas/Airport'
        aircraftRegistration:
          type: string
        from:
          type: string
        till:
          type: string
      required:
        - airport
        - aircraftRegistration
        - from
        - till

    Flight:
      type: object
      properties:
        departure:
          $ref: '#/components/schemas/Airport'
        destination:
          $ref: '#/components/schemas/Airport'
        callsign:
          type: string
        aircraftRegistration:
          type: string
        scheduledTimeOfDeparture:
          type: string
        scheduledTimeOfArrival:
          type: string
        departureTimeZone:
          type: string
        arrivalTimeZone:
          type: string
        type:
          $ref: '#/components/schemas/FlightType'
      required:
        - departure
        - destination
        - callsign
        - aircraftRegistration
        - scheduledTimeOfDeparture
        - scheduledTimeOfArrival
        - departureTimeZone
        - arrivalTimeZone
        - type

    ActiveFlight:
      type: object
      properties:
        flight:
          $ref: '#/components/schemas/Flight'
        altitude:
          type: integer
        speed:
          type: integer
        location:
          $ref: '#/components/schemas/Location'
        route:
          type: array
          items:
            $ref: '#/components/schemas/Location'
        locationTimestamp:
          type: string    
        actualDepartureTime:
          type: string
        estimatedTimeOfArrival:
          type: string
      required:
        - locationTimestamp
        - flight
        - altitude
        - speed
        - location
        - route
        - actualDepartureTime
        - estimatedTimeOfArrival

    Aircraft:
      type: object
      properties:
        aircraftRegistration:
          type: string
        serialNumber:
          type: string  
        name:
          type: string
        aircraftModelCode:
          type: string
        homeBase:
          type: string
        lastAirport:
          $ref: '#/components/schemas/Airport'
        capacity:
          type: integer
        yearOfConstruction:
          type: integer
        travelRange:
          type: integer
        speed:
          type: integer
        operationAltitude:
          type: integer  
        outlineImageUrl:
          type: string
        imageUrls:
          type: array
          items:
            type: string
      required:
        - aircraftRegistration
        - serialNumber
        - name
        - aircraftModelCode
        - homeBase
        - lastAirport
        - capacity
        - yearOfConstruction
        - outlineImageUrl
        - imageUrls
        - travelRange
        - speed
        - operationAltitude

    Impression:
      type: object
      properties:
        date:
          type: string
        imageUrl:
          type: string
        description:
          type: string  
      required:
        - date
        - imageUrl

    HighlightResponse:
      type: object
      properties:
        highlights:
          type: array
          items:
            $ref: '#/components/schemas/Highlight'
        page:
          type: integer
        pageSize:
          type: integer
      required:
        - highlights
        - page
        - pageSize

    Highlight:
      type: object
      properties:
        date:
          type: string
        imageUrl:
          type: string
          nullable: true
        title:
          type: string
        shortText:
          type: string
        longText:
          type: string
        timeStamp:
          type: string
        type:
          $ref: '#/components/schemas/HighlightType'
      required:
        - date
        - title
        - shortText
        - longText
        - timeStamp

    Feedback:
      type: object
      properties:
        ratings:
          type: array
          items:
            $ref: '#/components/schemas/FeedbackRating'
        questions:
          type: array
          items:
            $ref: '#/components/schemas/FeedbackQuestion'
        comment:
          type: string
      required:
        - ratings
        - questions
        - comment

    FeedbackRating:
      type: object
      properties:
        question:
          type: string
        rating:
          type: integer
      required:
        - question
        - rating

    FeedbackQuestion:
      type: object
      properties:
        question:
          type: string
        answer:
          type: string
      required:
        - question
        - answer

    PersonType:
      type: string
      enum:
        - PILOT
        - CREW_MEMBER
        - AVCON_JET

    FlightType:
      type: string
      enum:
        - OWNER
        - CHARTERED
        - EMPTY

    HighlightType:
      type: string
      enum:
        - SIMPLE
        - FLIGHT_SPIDER
        - FEEDBACK
